# Generated by Django 3.1.14 on 2023-02-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
